import os
import requests
import json
from dotenv import load_dotenv

def setup_rpc_exec_sql(url, key):
    """
    Checks if 'exec_sql' RPC exists. If not, provides instructions for manual setup.
    There is no API to create functions remotely without direct DB connection or an existing RPC.
    """
    print("Checking RPC 'exec_sql' availability...")
    
    rpc_sql = """
    CREATE OR REPLACE FUNCTION public.exec_sql(query text)
    RETURNS void
    LANGUAGE plpgsql
    SECURITY DEFINER
    AS $$
    BEGIN
      EXECUTE query;
    END;
    $$;
    """
    
    # Try to call it to see if it exists
    try:
        from supabase import create_client
        client = create_client(url, key)
        # Try a harmless query
        client.rpc('exec_sql', {'query': 'SELECT 1'}).execute()
        print("   [OK] RPC 'exec_sql' is active and ready.")
        return True
    except Exception as e:
        # If it fails, it likely doesn't exist
        print("   [!] RPC 'exec_sql' NOT FOUND or inaccessible.")
        print("   [ACTION REQUIRED] Please run the following SQL in your Supabase Dashboard (SQL Editor):")
        print("   ----------------------------------------------------------------")
        print(rpc_sql)
        print("   ----------------------------------------------------------------")
        print("   After running this, re-run this script to provision tables.")
        return False

def automate_supabase():
    load_dotenv("data/.env")
    url = os.getenv("SUPABASE_URL")
    access_token = os.getenv("SUPABASE_ACCESS_TOKEN")
    key = os.getenv("SUPABASE_KEY") # Use Service Role Key if available for max privs
    
    # 0. Check/Setup RPC
    if not setup_rpc_exec_sql(url, key):
        return

    # 1. SQL to Create Tables
    sql_script = """
    CREATE TABLE IF NOT EXISTS public.nexus_state (
        id BIGINT PRIMARY KEY,
        data JSONB NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS public.usage_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        provider TEXT NOT NULL,
        tokens BIGINT NOT NULL,
        cost_usd NUMERIC NOT NULL,
        timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    );

    -- Minimal security for automation (Admin access only for now)
    ALTER TABLE public.nexus_state ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.usage_logs ENABLE ROW LEVEL SECURITY;
    
    -- Drop existing if any and create open policy for admin
    DROP POLICY IF EXISTS "Admin Full Access" ON public.nexus_state;
    CREATE POLICY "Admin Full Access" ON public.nexus_state FOR ALL USING (true);
    
    DROP POLICY IF EXISTS "Admin Full Access" ON public.usage_logs;
    CREATE POLICY "Admin Full Access" ON public.usage_logs FOR ALL USING (true);
    """

    print("Executing SQL setup via RPC...")
    
    try:
        from supabase import create_client
        client = create_client(url, key)
        client.rpc('exec_sql', {'query': sql_script}).execute()
        print("[OK] Tables and Policies created successfully!")
    except Exception as e:
        print(f"Network Error: {e}")

if __name__ == "__main__":
    automate_supabase()
