import os
import time
import psycopg2
from dotenv import load_dotenv

def init_db_direct():
    print(">> Initializing Database via Direct Connection (PostgreSQL)...")
    
    # Load credentials
    load_dotenv("data/.env")
    
    db_pass = os.getenv("DB_PASSWORD")
    url = os.getenv("SUPABASE_URL")
    
    if not db_pass or not url:
        print("   [!] Missing credentials in .env (DB_PASSWORD or SUPABASE_URL)")
        return False
        
    project_ref = url.split("//")[1].split(".")[0]
    db_host = f"db.{project_ref}.supabase.co"
    db_user = "postgres"
    db_name = "postgres"
    
    # Connection String
    # postgres://postgres:[pass]@db.[ref].supabase.co:6543/postgres (Port 5432 or 6543)
    # Supabase uses 5432 for direct, 6543 for transaction pooler. We use 5432 for DDL.
    
    print(f"   Target: {db_host}:5432")
    
    try:
        conn = psycopg2.connect(
            host=db_host,
            database=db_name,
            user=db_user,
            password=db_pass,
            port=5432
        )
        conn.autocommit = True
        cursor = conn.cursor()
        
        # 1. Define RPC Function (exec_sql)
        print("   -> Creating 'exec_sql' RPC function...")
        rpc_sql = """
        CREATE OR REPLACE FUNCTION public.exec_sql(query text)
        RETURNS void
        LANGUAGE plpgsql
        SECURITY DEFINER
        AS $$
        BEGIN
          EXECUTE query;
        END;
        $$;
        """
        cursor.execute(rpc_sql)
        print("      [OK] RPC function created.")
        
        # 2. Setup Tables (Nexus State & Usage Logs)
        print("   -> Creating initial tables...")
        tables_sql = """
        CREATE TABLE IF NOT EXISTS public.nexus_state (
            id BIGINT PRIMARY KEY,
            data JSONB NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
        );

        CREATE TABLE IF NOT EXISTS public.usage_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            provider TEXT NOT NULL,
            tokens BIGINT NOT NULL,
            cost_usd NUMERIC NOT NULL,
            timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
        );
        """
        cursor.execute(tables_sql)
        print("      [OK] Tables created.")
        
        # 3. Security (RLS)
        print("   -> Applying Security Policies...")
        security_sql = """
        ALTER TABLE public.nexus_state ENABLE ROW LEVEL SECURITY;
        ALTER TABLE public.usage_logs ENABLE ROW LEVEL SECURITY;
        
        DROP POLICY IF EXISTS "Admin Full Access" ON public.nexus_state;
        CREATE POLICY "Admin Full Access" ON public.nexus_state FOR ALL USING (true);
        
        DROP POLICY IF EXISTS "Admin Full Access" ON public.usage_logs;
        CREATE POLICY "Admin Full Access" ON public.usage_logs FOR ALL USING (true);
        """
        cursor.execute(security_sql)
        print("      [OK] Security policies applied.")

        cursor.close()
        conn.close()
        print("\n>> DATABASE INITIALIZATION COMPLETE [SUCCESS]")
        return True
        
    except Exception as e:
        print(f"\n   [FAIL] Database Connection Error: {e}")
        # Hint about library
        if "psycopg2" in str(e):
             print("   Make sure psycopg2 or psycopg2-binary is installed: pip install psycopg2-binary")
        return False

if __name__ == "__main__":
    init_db_direct()
