import psycopg2
import os
import json
from dotenv import load_dotenv

def run():
    report = {"status": "starting", "steps": []}
    def log_step(name, success, info=""):
        report["steps"].append({"step": name, "success": success, "info": info})
        with open("supabase_init_report.json", "w") as f:
            json.dump(report, f, indent=4)

    load_dotenv("data/.env")
    db_pass = os.getenv("DB_PASSWORD")
    db_url = os.getenv("SUPABASE_URL")
    
    if not db_pass or not db_url:
        log_step("env_check", False, "Missing credentials in .env")
        return

    host_ref = db_url.split("//")[1].split(".")[0]
    conn_host = f"db.{host_ref}.supabase.co"
    
    try:
        log_step("connecting", True, f"Connecting to {conn_host}")
        conn = psycopg2.connect(
            host=conn_host,
            database="postgres",
            user="postgres",
            password=db_pass,
            port="5432",
            connect_timeout=10
        )
        cur = conn.cursor()
        
        # 1. Create nexus_state
        try:
            cur.execute("""
            CREATE TABLE IF NOT EXISTS public.nexus_state (
                id BIGINT PRIMARY KEY,
                data JSONB NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
            );
            """)
            log_step("create_nexus_state", True)
        except Exception as e:
            log_step("create_nexus_state", False, str(e))
            conn.rollback()

        # 2. Create usage_logs
        try:
            cur.execute("""
            CREATE TABLE IF NOT EXISTS public.usage_logs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                provider TEXT NOT NULL,
                tokens BIGINT NOT NULL,
                cost_usd NUMERIC NOT NULL,
                timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
            );
            """)
            log_step("create_usage_logs", True)
        except Exception as e:
            log_step("create_usage_logs", False, str(e))
            conn.rollback()

        # 3. Security
        try:
            cur.execute("ALTER TABLE IF EXISTS public.nexus_state ENABLE ROW LEVEL SECURITY;")
            cur.execute("ALTER TABLE IF EXISTS public.usage_logs ENABLE ROW LEVEL SECURITY;")
            cur.execute("DROP POLICY IF EXISTS \"Admin Access\" ON public.nexus_state;")
            cur.execute("CREATE POLICY \"Admin Access\" ON public.nexus_state FOR ALL USING (true);")
            cur.execute("DROP POLICY IF EXISTS \"Admin Access\" ON public.usage_logs;")
            cur.execute("CREATE POLICY \"Admin Access\" ON public.usage_logs FOR ALL USING (true);")
            log_step("configure_security", True)
        except Exception as e:
            log_step("configure_security", False, str(e))
            conn.rollback()

        conn.commit()
        
        # 4. Final Verification
        cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';")
        tables = [r[0] for r in cur.fetchall()]
        log_step("final_verify", True, f"Found tables: {tables}")
        
        report["status"] = "success"
        log_step("complete", True)
        
        cur.close()
        conn.close()
        
    except Exception as e:
        log_step("critical_error", False, str(e))
        report["status"] = "failed"

if __name__ == "__main__":
    run()
