-- NEXUS MASTER GEN: Supabase Schema Initialization
-- Execute this in the Supabase SQL Editor

-- 1. Table for System State
CREATE TABLE IF NOT EXISTS public.nexus_state (
    id BIGINT PRIMARY KEY,
    data JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table for Usage Logs
CREATE TABLE IF NOT EXISTS public.usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    tokens BIGINT NOT NULL,
    cost_usd NUMERIC NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Recommended)
ALTER TABLE public.nexus_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usage_logs ENABLE ROW LEVEL SECURITY;

-- Note: In a real production app, you would add specific policies for the API Key used.
