"""
Script de Prueba Manual - Guía de Verificación
Este script te guiará para probar manualmente la interfaz web
"""

print("=" * 70)
print("GUÍA DE PRUEBA MANUAL - NEXUS MASTER GEN")
print("=" * 70)

print("\n📋 PASOS DE VERIFICACIÓN:\n")

print("1️⃣ VERIFICAR QUE LA INTERFAZ CARGA")
print("   - Abre: http://localhost:8550")
print("   - Deberías ver: NEXUS MASTER GEN con 4 pestañas")
print("   - Estado: ONLINE (verde) en la esquina superior derecha")
print()

print("2️⃣ PROBAR MÓDULO BRAIN (Chat IA)")
print("   - Click en pestaña BRAIN")
print("   - Escribe: 'Quiero crear una app de tareas con diseño futurista'")
print("   - Click en el botón de enviar (ícono de avión)")
print("   - Espera la respuesta de la IA")
print()

print("3️⃣ VERIFICAR LOGS EN MATRIX")
print("   - Click en pestaña MATRIX")
print("   - Deberías ver logs como:")
print("     • 🧠 ANALIZANDO SOLICITUD: 'Quiero crear...'")
print("     • 📡 Conectando con Núcleo Groq...")
print("     • ✅ Respuesta recibida de Groq.")
print()

print("4️⃣ GENERAR PROYECTO EN FACTORY")
print("   - Click en pestaña FACTORY")
print("   - Scroll hacia abajo para ver los campos")
print("   - Nombre del proyecto: 'TaskMaster'")
print("   - Descripción: 'App de gestión de tareas con diseño cyberpunk'")
print("   - Click en la tarjeta 'Liquid Glass' (primera opción)")
print("   - Click en 'GENERAR_PROYECTO_BUTTON'")
print()

print("5️⃣ MONITOREAR PROGRESO EN MATRIX")
print("   - Vuelve a la pestaña MATRIX")
print("   - Deberías ver la secuencia completa:")
print("     • TRINITY_START: TaskMaster")
print("     • SCAFFOLD_OK: Base structure created")
print("     • PILLAR_INJECT: SyncCore, BackendManager, Design Tokens")
print("     • AI_GEN_START: Generating custom logic...")
print("     • AI_GEN_OK: Custom logic injected. (o WARN si falla)")
print("     • TRINITY_COMPLETE: TaskMaster is ready.")
print()

print("6️⃣ VERIFICAR EN BRAIN")
print("   - Vuelve a la pestaña BRAIN")
print("   - Deberías ver un mensaje final:")
print("     '✅ Protocolo Trinity Completado. Proyecto listo en: C:\\...\\factory\\TaskMaster'")
print()

print("7️⃣ VERIFICAR ARCHIVOS GENERADOS")
print("   - Abre el explorador de archivos")
print("   - Navega a: C:\\Users\\Admin\\Desktop\\ATOLLI_ORQUESTADOR\\factory\\TaskMaster")
print("   - Verifica que existan:")
print("     • web_portal/main.py")
print("     • staff_app/main.py")
print("     • shared/sync_core.py")
print("     • shared/backend_manager.py")
print("     • shared/design_tokens.py")
print()

print("=" * 70)
print("✅ CRITERIOS DE ÉXITO:")
print("=" * 70)
print("• La interfaz carga sin errores")
print("• BRAIN responde a mensajes")
print("• MATRIX muestra logs en tiempo real")
print("• FACTORY genera proyectos completos")
print("• Los archivos se crean en factory/")
print()

print("⚠️ SI ALGO FALLA:")
print("• Revisa la consola del servidor (donde corre debug_web_launcher.py)")
print("• Verifica que las API keys estén configuradas en CONFIG")
print("• Asegúrate de que el puerto 8550 no esté bloqueado")
print()

print("=" * 70)
print("🚀 LISTO PARA PROBAR")
print("=" * 70)
print("\nAbre tu navegador en: http://localhost:8550")
print("Sigue los pasos anteriores y reporta cualquier problema.")
print()
